module.exports.AnswerDeck = [
    {id: 1, text: 'Pingas', type: 'Answer'},
    {id: 2, text: `Farting on someone's pillow to give them pinkeye`, type: 'Answer'},
    {id: 3, text: 'A puppy and a kitten wearing people clothes', type: 'Answer'},
    {id: 4, text: 'A tricked out 1964 Impala Low Rider', type: 'Answer'},
    {id: 5, text: 'Shouting the N-Word like a French police siren', type: 'Answer'},
    {id: 6, text: 'Doing all of the drugs', type: 'Answer'},
    {id: 7, text: 'Drinking polluted sea water', type: 'Answer'},
    {id: 8, text: 'Shredding the gnar!', type: 'Answer'},
    {id: 9, text: 'GET TO THE CHOPPA!!!', type: 'Answer'},
    {id: 10, text: 'Open the door, get on the floor, everybody walk the dinosaur!', type: 'Answer'},
    {id: 11, text: 'Taking an aqua-dump', type: 'Answer'},
    {id: 12, text: 'Putting hand-sanitizer in the microwave', type: 'Answer'},
    {id: 13, text: "50mg of SSRI's daily", type: 'Answer'},
    {id: 14 , text: "2 Girls, 1 Cup", type: 'Answer'},
    {id: 15, text: "72 Virgins", type: 'Answer'},
    {id: 16, text: "A Meth-Fentanyl Speedball", type: 'Answer'},
    {id: 17, text: "Pretending to be handicapped to get a better parking spot", type: 'Answer'},
    {id: 18, text: "Pretending to be handicapped to cut the line at amusement parks", type: 'Answer'},
    {id: 19, text: "A ball of earwax, semen, and toenail clippings.", type:"Answer"},
    {id: 20, text: "Magic Beans", type: "Answer"},    
    {id: 21, text: "A horse sized duck", type: 'Answer'},
    {id: 22, text: "100 duck sized horses", type: 'Answer'},
    {id: 23, text: "Clown Porn *honk honk*", type: 'Answer'},
    {id: 24, text: "Reading my erotic fan-fiction", type: 'Answer'},
    {id: 25, text: "Aggressively Fortnite dancing", type: 'Answer'},
    {id: 26, text: "Eating whale meat. Not for sport, or tradition, but for fun... Fuck whales", type: 'Answer'},
    {id: 27, text: "Burning the American flag", type: 'Answer'},
    {id: 28, text: "Introducing crack to vulnerable minority communities", type: 'Answer'},
    {id: 29, text: "A dangerous amount of yellow-cake uranium ", type: 'Answer'},
    {id: 30, text: "Betting on daycare fight clubs", type: 'Answer'},
    {id: 31, text: "#3, The Intimidator, Dale Earnhardt", type: 'Answer'},
    {id: 32, text: "The Macho Man Randy Savage! OH YEAAAAAAH!", type: 'Answer'},
    {id: 33, text: "An eigth of bubonic chronic", type: 'Answer'},
    {id: 34, text: "Cheating on my taxes", type: 'Answer'},
    {id: 35, text: "Trash pandas", type: 'Answer'},
    {id: 36, text: "A tallboy can of Whoopass", type: 'Answer'},
    {id: 37, text: "A firm bitch slap", type: 'Answer'},
    {id: 38, text: "A child sex-trafficking coverup", type: 'Answer'},
    {id: 39, text: "Getting lockjaw from bad molly at a music festival", type: 'Answer'},
    {id: 40, text: "A Bleached Anus", type: 'Answer'},
    {id: 41, text: "My original Sonic the Hedgehog character", type: 'Answer'},
    {id: 42, text: "Racism in classic films", type: 'Answer'},
    {id: 43, text: "Talking like 1940's detective during sex", type: 'Answer'},
    {id: 44, text: "Trampled to death while Travis Scott sings in autotune", type: 'Answer'},
    {id: 45, text: "Giving 110% Percent", type: 'Answer'},
    {id: 46, text: "Pikachu!", type: 'Answer'},
    {id: 47, text: "Ritalistic cannibalism", type: 'Answer'},
    {id: 48, text: "Shaving festive holiday symbols into your pubes", type: 'Answer'},
    {id: 49, text: "Dingleberries", type: 'Answer'},
    {id: 50, text: "Ordering a drone strike on a Pakistani wedding", type: 'Answer'},
    {id: 51, text: "Toxoplasmosis", type: 'Answer'},
    {id: 52, text: "Not being drunk enough", type: 'Answer'},
    {id: 53, text: "Going to Thai Prison for drug smuggling", type: 'Answer'},
    {id: 54, text: "Throwing up gang signs", type: 'Answer'},
    {id: 55, text: "Watching cat videos", type: 'Answer'},
    {id: 56, text: "A cartoon camel enjoying the smooth, refreshing taste of a cigarette.", type: 'Answer'},
    {id: 57, text: "Ranting about the number of CIA agents working for major news networks", type: 'Answer'},
    {id: 58, text: "Tastefully performing in blackface", type: 'Answer'},
    {id: 59, text: "Slavery, but with extra steps." , type: 'Answer'},
    {id: 60, text: "A certain je ne sais quoi", type: 'Answer'},
    {id: 61, text: "Child beauty pagents", type: 'Answer'},
    {id: 62, text: "A front for organized crime", type: 'Answer'},
    {id: 63, text: "The dead body in the back of my rental car", type: 'Answer'},
    {id: 64, text: "Recreational arson", type: 'Answer'},
    {id: 65, text: "A worker's revolution", type: 'Answer'},
    {id: 66, text: "Mein Kampf: The Movie", type: 'Answer'},
    {id: 67, text: "Mein Kampf 2: Electric Boogaloo", type: 'Answer'},
    {id: 68, text: "Insider trading during the COVID pandemic", type: 'Answer'},
    {id: 69, text: "A streaming series with preachy political themes", type: 'Answer'},
    {id: 70, text: "Furiously masturbating in the produce section", type: 'Answer'},
    {id: 71, text: "A daylight bank heist and runnning gun battle", type: 'Answer'},
    {id: 72, text: "A cooler full of human organs", type: 'Answer'},
    {id: 73, text: "Live streaming a driveby shooting", type: 'Answer'},    
    {id: 74, text: "A cute, fuzzy koala, but it has chlamydia." , type: 'Answer'},
    {id: 75, text: "Culturally mandated genital mutilation" , type: 'Answer'},
    {id: 76, text: "Intentionally spreading monkeypox" , type: 'Answer'},
    {id: 77, text: "A digeridoo " , type: 'Answer'},
    {id: 78, text: "Drunken brawls at sporting events!", type: 'Answer'},
    {id: 79, text: "A fart so powerful that it wakes the giants from their thousand-year slumber", type: 'Answer'},
    {id: 80, text: "Casual domestic violence", type: 'Answer'},
    {id: 81, text: "A Gypsy curse.", type: 'Answer'},
    {id: 82, text: "You've activated my trap card!", type: 'Answer'},
    {id: 83, text: "A micropig wearing a tiny raincoat and booties", type: 'Answer'},
    {id: 84, text: "Childhood obesity", type: 'Answer'},
   
]

module.exports.PromptDeck = [
    {id: 1, text: `________ is why I'm banned from all Disney ThemeParks`, type: 'Prompt'},
    {id: 2, text: `________ , it's what's for dinner`, type: 'Prompt'},
    {id: 3, text: `Truly, the greatest pain and greatest pleasure that life can off is ________`, type: 'Prompt'},
    {id: 4, text: `When you wish up on  ________ your dreams come true~`, type: 'Prompt'},
    {id: 5, text: `My boss says I'd be management material if I could just stop ________`, type:'Prompt'},
    {id: 6, text: `If I had a dollar for every time I've seen someone ________ , I'd be a millionaire`, type:'Prompt'},
    {id: 7, text: `My new catch phrase is ________ !`, type:'Prompt'},
    {id: 8, text: `Gentlemen.... Behold,  ________!`, type:'Prompt'},
    {id: 9, text: `I'm coming out of retirement to take one last run at the ________ Championship Circuit`, type:'Prompt'},
    {id: 10, text: `Watch me whip, and watch me ________`, type:'Prompt'},
    {id: 11, text: `WATCHU GONNA DO WHEN ________ RUNS WILD ON YOU BROTHER?`, type:'Prompt'},
    {id: 12, text: `Who's that Pokemon? It's ________ !`, type:'Prompt'},
    {id: 13, text: `Percocet,  ________ , Percocet`, type:'Prompt'},
    {id: 14, text: `I heard ________ is headlining Coachella this year`, type:'Prompt'},
    {id: 15, text: `________`, type:'Prompt'},
    {id: 16, text: `Raindrop, drop top, ________ in the hotbox`, type:'Prompt'},
    {id: 17, text: `Fuck you, Mom and Dad! ________ isn't a phase! It's my life!`, type:'Prompt'},
    {id: 18, text: `Here to receive the Lifetime Achievement Award for  ________ is *name of judge* `, type:'Prompt'},
    {id: 19, text: `It's January 6th, but instead of the election, everyone is rioting over ________ `, type:'Prompt'},
    {id: 20, text: `CASH ME  ________ HOW BOUT DAT? `, type:'Prompt'}

]