-- DROP DATABASE CardGame;
-- CREATE DATABASE CardGame;
\c cardgame;
-- CREATE SCHEMA cardgame;

CREATE TABLE users (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  username VARCHAR(200),
  password VARCHAR(50),
  avatar VARCHAR(500)
);
CREATE TABLE prompts (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  body VARCHAR(500) NOT NULL,
  user_id INTEGER DEFAULT NULL REFERENCES users(id),
  NSFW BOOLEAN NOT NULL
);
CREATE TABLE answers (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  body VARCHAR(500) NOT NULL,
  user_id INTEGER DEFAULT NULL REFERENCES users(id),
  NSFW BOOLEAN NOT NULL
);

\COPY prompts(body, NSFW) FROM '/Users/codein92/Desktop/prompts.csv' CSV HEADER;
\COPY answers(body, NSFW) FROM '/Users/codein92/Desktop/answers.csv'
 CSV HEADER;
CREATE INDEX user_id_index ON users USING HASH (id);